# Parameter tuning for simulate-last heuristic.

This notebook loads the results of different simulate-last heuristics applied to various scheduling problems,
performs summary statistics, and conducts significance testing on the results. It generates a LaTeX table summarizing the findings to be reported in the article.

Instructions:

- Run cells below with b_with_tardiness set to True or False to compare results with and without tardiness in the objective function.
- It will save .tex file with the results table in the `latex` directory.
- Copy the generated .tex files to Overleaf results folder.

In [6]:
from pathlib import Path

import pandas as pd

# Data loading

In [7]:
b_with_tardiness = False

DATA_DIR = Path("../results")
all_csv_files = """JobShopFullStoch_2025-06-15_11-46-14.csv
FlexibleJobShopFullStochNoTard_2025-06-15_11-45-42.csv
JobShop_2025-06-15_11-46-08.csv
FlexibleJobShop_2025-06-15_11-45-30.csv
FlexibleJobShopNoTard_2025-06-15_11-45-38.csv
ParallelMachinesFullStoch_2025-06-15_11-46-38.csv
ParallelMachinesFullStochNoTard_2025-06-15_11-46-49.csv
ParallelMachinesNoTard_2025-06-15_11-46-43.csv
HybridFlowShopFullStochNoTard_2025-06-15_11-46-03.csv
ParallelMachines_2025-06-15_11-46-32.csv
HybridFlowShopFullStoch_2025-06-15_11-45-53.csv
HybridFlowShopNoTard_2025-06-15_11-45-57.csv
HybridFlowShop_2025-06-15_11-45-46.csv
OpenShopFullStochNoTard_2025-06-15_11-45-18.csv
OpenShopFullStoch_2025-06-15_11-45-10.csv
OpenShopNoTard_2025-06-15_11-45-17.csv
OpenShop_2025-06-15_11-45-04.csv
JobShopFullStochNoTard_2025-06-15_11-46-32.csv
JobShopNoTard_2025-06-15_11-46-26.csv
FlexibleJobShopFullStoch_2025-06-15_11-45-30.csv""".split('\n')
problem_order = ['OpenShop', 'ParallelMachines', 'HybridFlowShop', 'JobShop', 'FlexibleJobShop']
def find_with_part(file_names, part):
    """Find all file names that contain a specific part."""
    return [name for name in file_names if part == name.split('_')[0]][0]

if b_with_tardiness:
    file_names_per_exp_group = {
        "p = 0.3": [
            find_with_part(all_csv_files, problem_name)                
            for problem_name in problem_order
            ],
        "p = 1.0": [
            find_with_part(all_csv_files, problem_name + "FullStoch")
            for problem_name in problem_order
            ],
        }  # the key denotes a group of experiments
else:
    file_names_per_exp_group = {
        "p = 0.3":[
            find_with_part(all_csv_files, problem_name + "NoTard")
            for problem_name in problem_order
            ],
        "p = 1.0": [
            find_with_part(all_csv_files, problem_name + "FullStochNoTard")
            for problem_name in problem_order
            ],
        }  # without tardiness
print(file_names_per_exp_group)
dfs = {}
simheuristics = [f"sim_last_{i + 1}" for j in range(20) for i in range(8)]
for exp_group, file_names in file_names_per_exp_group.items():
    dfs[exp_group] = {}
    for file_name in file_names:
        dfs[exp_group][file_name] = pd.read_csv(DATA_DIR / file_name)
        dfs[exp_group][file_name]["simheuristic"] = simheuristics  # I forgot to change the name
        display(dfs[exp_group][file_name].head(15))

{'p = 0.3': ['OpenShopNoTard_2025-06-15_11-45-17.csv', 'ParallelMachinesNoTard_2025-06-15_11-46-43.csv', 'HybridFlowShopNoTard_2025-06-15_11-45-57.csv', 'JobShopNoTard_2025-06-15_11-46-26.csv', 'FlexibleJobShopNoTard_2025-06-15_11-45-38.csv'], 'p = 1.0': ['OpenShopFullStochNoTard_2025-06-15_11-45-18.csv', 'ParallelMachinesFullStochNoTard_2025-06-15_11-46-49.csv', 'HybridFlowShopFullStochNoTard_2025-06-15_11-46-03.csv', 'JobShopFullStochNoTard_2025-06-15_11-46-32.csv', 'FlexibleJobShopFullStochNoTard_2025-06-15_11-45-42.csv']}

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_1,0,7861.208,174.457114,1000,7412.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.094305,29.911403,300.005708
1,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_2,0,7857.044,201.050382,1000,7299.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.171650,29.884220,300.055871
2,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_3,0,7827.151,174.493926,1000,7438.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.158773,29.927795,300.086568
3,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_4,0,7723.682,167.397983,1000,7357.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.133166,29.897884,300.031049
4,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_5,0,7832.644,148.562631,1000,7546.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.193972,29.874010,300.067981
5,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_6,0,7861.319,157.302572,1000,7466.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.309436,29.770128,300.079565
6,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_7,0,7921.913,144.655043,1000,7606.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.092365,29.963334,300.055699
7,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_8,0,7698.995,114.356849,1000,7515.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.151892,29.877517,300.029409
8,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_1,1,8441.436,181.768688,1000,7965.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.350751,29.669555,300.020306
9,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_2,1,8589.173,201.130040,1000,8080.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.195330,29.831544,300.026874
10,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_3,1,8611.611,174.659834,1000,8205.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.186654,29.886842,300.073497
11,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_4,1,8545.464,172.661746,1000,8163.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.191735,29.829980,300.021715
12,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_5,1,8570.323,162.349539,1000,8224.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.115723,29.971661,300.087384
13,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_6,1,8606.232,164.124612,1000,8256.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.086683,30.006209,300.092892
14,OpenShopNoTard_2025-06-15_11-45-17,OpenShopNoTard,sim_last_7,1,8701.369,150.492873,1000,8386.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.283819,29.790164,300.073982

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_1,0,67.957,2.526490,1000,65.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.360394,29.648143,300.008538
1,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_2,0,69.607,2.961174,1000,66.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.346234,29.671284,300.017519
2,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_3,0,65.236,2.412945,1000,63.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.357536,29.650408,300.007944
3,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_4,0,68.777,2.973091,1000,67.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.365502,29.684993,300.050495
4,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_5,0,72.004,1.712888,1000,71.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.358503,29.667810,300.026313
5,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_6,0,63.111,2.068013,1000,62.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.587119,29.437541,300.024660
6,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_7,0,69.165,1.975291,1000,68.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.346995,29.686791,300.033786
7,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_8,0,68.881,2.393917,1000,67.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.441812,29.575790,300.017602
8,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_1,1,78.348,3.347969,1000,75.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.363965,29.662423,300.026388
9,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_2,1,77.904,3.072260,1000,75.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.354714,29.687826,300.042541
10,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_3,1,77.372,2.107514,1000,76.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.348567,29.662855,300.011423
11,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_4,1,77.201,2.703812,1000,75.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.354465,29.647547,300.002012
12,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_5,1,84.285,2.808518,1000,82.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.340400,29.687905,300.028305
13,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_6,1,76.053,2.092891,1000,75.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.348558,29.677382,300.025940
14,ParallelMachinesNoTard_2025-06-15_11-46-43,ParallelMachinesNoTard,sim_last_7,1,79.727,2.855603,1000,78.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.355136,29.665319,300.020455

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_1,0,149.741,4.068897,1000,139.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.151567,29.891925,300.043491
1,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_2,0,150.252,4.518462,1000,139.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.150596,29.860854,300.011450
2,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_3,0,151.511,3.793663,1000,143.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.146354,29.895082,300.041436
3,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_4,0,149.694,4.064525,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.149159,29.892405,300.041564
4,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_5,0,148.826,3.861570,1000,142.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.153581,29.894257,300.047838
5,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_6,0,149.017,3.683302,1000,142.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.147518,29.887682,300.035201
6,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_7,0,149.984,3.175176,1000,145.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.150084,29.855306,300.005389
7,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_8,0,149.356,3.479549,1000,143.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.154641,29.874167,300.028808
8,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_1,1,161.054,4.924945,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.152888,29.886732,300.039620
9,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_2,1,160.103,4.445941,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.214036,29.817903,300.031939
10,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_3,1,160.391,4.679543,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.149953,29.905414,300.055367
11,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_4,1,160.398,4.442251,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.152620,29.891382,300.044001
12,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_5,1,159.043,3.835512,1000,154.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.144483,29.888303,300.032786
13,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_6,1,159.167,4.460169,1000,151.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.153039,29.917425,300.070464
14,HybridFlowShopNoTard_2025-06-15_11-45-57,HybridFlowShopNoTard,sim_last_7,1,158.285,4.001472,1000,151.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.149497,29.918722,300.068218

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_1,0,12707.446,245.697076,1000,12247.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.097030,29.906997,300.004027
1,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_2,0,12764.576,239.684472,1000,12356.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.095778,29.964407,300.060185
2,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_3,0,12906.635,238.977362,1000,12494.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.104464,29.989850,300.094314
3,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_4,0,12863.502,229.347714,1000,12430.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.156857,29.903405,300.060261
4,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_5,0,12935.242,197.815382,1000,12605.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.099132,29.969739,300.068871
5,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_6,0,12736.966,230.518921,1000,12358.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.094814,29.972125,300.066939
6,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_7,0,13058.806,174.126007,1000,12833.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.099829,29.966669,300.066498
7,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_8,0,12896.135,186.824476,1000,12573.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.160552,29.912703,300.073255
8,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_1,1,12693.630,269.540582,1000,12076.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.100332,29.912173,300.012505
9,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_2,1,12688.231,272.739358,1000,12034.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.174853,29.891431,300.066284
10,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_3,1,12640.428,240.086428,1000,12138.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.163846,29.858065,300.021912
11,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_4,1,12674.481,223.731718,1000,12193.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.097733,29.909191,300.006924
12,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_5,1,12632.522,212.001706,1000,12238.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.116337,29.969306,300.085644
13,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_6,1,12518.177,203.226105,1000,12163.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.257955,29.818397,300.076352
14,JobShopNoTard_2025-06-15_11-46-26,JobShopNoTard,sim_last_7,1,12551.476,204.679700,1000,12258.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.107610,29.961958,300.069568

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_1,0,138.610,3.980942,1000,131.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.225135,29.789175,300.014310
1,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_2,0,139.827,3.458478,1000,133.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.256243,29.823888,300.080131
2,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_3,0,142.028,3.338745,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.224289,29.818986,300.043276
3,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_4,0,139.456,3.550502,1000,133.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.225479,29.801748,300.027227
4,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_5,0,139.192,2.663670,1000,136.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.228377,29.774050,300.002427
5,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_6,0,137.898,3.085060,1000,134.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.228934,29.851824,300.080757
6,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_7,0,137.930,2.630798,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.224773,29.844366,300.069139
7,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_8,0,138.000,2.866357,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.223576,29.833999,300.057575
8,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_1,1,153.080,3.934921,1000,146.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.223499,29.881268,300.104767
9,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_2,1,154.314,3.394614,1000,147.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.233171,29.854299,300.087470
10,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_3,1,154.011,4.265780,1000,146.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.225773,29.819895,300.045668
11,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_4,1,155.447,3.969281,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.237476,29.894626,300.132102
12,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_5,1,154.226,2.999154,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.219622,29.824490,300.044112
13,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_6,1,155.535,2.924855,1000,151.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.225136,29.813211,300.038347
14,FlexibleJobShopNoTard_2025-06-15_11-45-38,FlexibleJobShopNoTard,sim_last_7,1,155.432,2.048262,1000,154.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.222433,29.830539,300.052973

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_1,0,8485.597,284.059343,1000,7354.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.095880,29.925234,300.021114
1,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_2,0,8775.669,292.742172,1000,7666.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.095262,29.918261,300.013523
2,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_3,0,8592.740,291.132637,1000,7568.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.233978,29.814247,300.048225
3,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_4,0,8460.256,291.436145,1000,7516.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.225084,29.846799,300.071883
4,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_5,0,8696.453,298.921611,1000,7650.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.091510,29.909093,300.000603
5,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_6,0,8569.771,285.449685,1000,7584.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.092544,29.921238,300.013782
6,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_7,0,8537.456,295.098512,1000,7635.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.273816,29.741248,300.015064
7,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_8,0,8445.752,288.355164,1000,7482.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.295061,29.721480,300.016541
8,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_1,1,9117.504,307.361348,1000,8005.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.244783,29.800639,300.045422
9,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_2,1,9212.910,306.455928,1000,8075.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.264934,29.742068,300.007002
10,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_3,1,9125.304,297.238843,1000,8137.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.091940,29.919267,300.011207
11,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_4,1,9187.110,299.640468,1000,8131.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.120902,29.894905,300.015807
12,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_5,1,9126.330,302.849846,1000,8108.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.185450,29.838436,300.023886
13,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_6,1,9242.638,298.977820,1000,8192.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.381778,29.695392,300.077170
14,OpenShopFullStochNoTard_2025-06-15_11-45-18,OpenShopFullStochNoTard,sim_last_7,1,9134.131,297.620802,1000,8087.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.129088,29.960112,300.089200

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_1,0,72.243,4.753099,1000,66.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.359639,29.688707,300.048346
1,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_2,0,78.692,5.008307,1000,73.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.347004,29.681029,300.028033
2,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_3,0,72.157,4.236077,1000,66.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.349941,29.655864,300.005805
3,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_4,0,67.572,4.281217,1000,62.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.352778,29.688115,300.040893
4,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_5,0,74.612,4.193979,1000,71.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.353334,29.670625,300.023959
5,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_6,0,69.059,4.238811,1000,66.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.349356,29.676630,300.025986
6,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_7,0,68.370,4.330716,1000,64.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.368832,29.642498,300.011331
7,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_8,0,70.197,4.222581,1000,65.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.350415,29.683833,300.034248
8,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_1,1,87.962,4.742843,1000,81.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.357025,29.678114,300.035139
9,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_2,1,78.758,4.998743,1000,72.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.394761,29.648595,300.043356
10,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_3,1,88.686,5.164630,1000,83.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.358447,29.659646,300.018092
11,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_4,1,81.223,5.236914,1000,77.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.349421,29.651503,300.000925
12,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_5,1,85.675,5.288608,1000,80.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.350654,29.661398,300.012053
13,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_6,1,81.209,5.243979,1000,75.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.403269,29.620656,300.023925
14,ParallelMachinesFullStochNoTard_2025-06-15_11-...,ParallelMachinesFullStochNoTard,sim_last_7,1,88.967,5.194026,1000,83.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,270.361430,29.659878,300.021308

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_1,0,161.243,6.899852,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.154513,29.917869,300.072381
1,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_2,0,161.079,6.649268,1000,139.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.210941,29.862852,300.073793
2,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_3,0,160.726,6.735349,1000,142.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.146982,29.871205,300.018187
3,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_4,0,162.223,7.031875,1000,143.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.151568,29.867305,300.018873
4,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_5,0,160.750,6.928311,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.150980,29.856408,300.007388
5,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_6,0,160.358,6.952542,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.163881,29.850996,300.014877
6,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_7,0,161.470,6.999221,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.150686,29.888731,300.039417
7,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_8,0,160.141,6.565601,1000,141.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.148883,29.910419,300.059302
8,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_1,1,170.171,6.935543,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.148064,29.874772,300.022836
9,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_2,1,170.757,6.806758,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.155322,29.862849,300.018170
10,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_3,1,171.363,7.089516,1000,149.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.153858,29.849077,300.002935
11,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_4,1,171.930,7.218525,1000,151.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.160796,29.840173,300.000969
12,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_5,1,169.920,7.087990,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.155678,29.882990,300.038668
13,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_6,1,170.073,7.117701,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.152724,29.911232,300.063956
14,HybridFlowShopFullStochNoTard_2025-06-15_11-46-03,HybridFlowShopFullStochNoTard,sim_last_7,1,171.114,6.895724,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.153466,29.899643,300.053109

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_1,0,13346.830,411.201120,1000,12247.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.144177,29.928137,300.072314
1,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_2,0,13307.306,417.888239,1000,12245.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.101877,29.907120,300.008997
2,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_3,0,13287.546,394.626487,1000,12361.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.120581,29.905698,300.026279
3,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_4,0,13340.955,407.906910,1000,12445.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.192612,29.879353,300.071965
4,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_5,0,13374.811,407.641903,1000,12398.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.095193,29.972297,300.067490
5,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_6,0,13450.525,402.898299,1000,12511.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.154171,29.888961,300.043133
6,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_7,0,13431.809,414.322168,1000,12408.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.094429,29.929350,300.023778
7,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_8,0,13672.299,419.808904,1000,12593.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.096339,29.984802,300.081141
8,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_1,1,13158.340,410.712080,1000,12102.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.099109,29.955159,300.054268
9,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_2,1,13008.296,401.380680,1000,11920.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.169496,29.906838,300.076334
10,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_3,1,13223.707,413.620260,1000,12150.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.100806,29.911855,300.012662
11,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_4,1,13321.061,404.085319,1000,12232.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.113377,29.912256,300.025633
12,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_5,1,13295.032,407.161063,1000,12175.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.242051,29.792583,300.034633
13,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_6,1,13132.663,414.119463,1000,11976.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.187467,29.868349,300.055815
14,JobShopFullStochNoTard_2025-06-15_11-46-32,JobShopFullStochNoTard,sim_last_7,1,13184.655,413.771343,1000,12115.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.097791,29.932383,300.030174

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_1,0,146.136,6.754369,1000,132.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.250873,29.826563,300.077435
1,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_2,0,148.155,6.734462,1000,132.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.252765,29.813960,300.066725
2,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_3,0,146.839,7.005218,1000,132.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.216419,29.793622,300.010041
3,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_4,0,146.523,6.827992,1000,134.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.217500,29.816691,300.034191
4,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_5,0,147.880,7.137619,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.234400,29.781580,300.015980
5,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_6,0,147.033,6.823775,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.224468,29.785363,300.009831
6,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_7,0,147.523,6.927155,1000,135.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.231879,29.855350,300.087229
7,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_8,0,147.132,7.031968,1000,136.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.221528,29.872534,300.094062
8,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_1,1,164.648,7.683885,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.264241,29.821073,300.085314
9,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_2,1,161.971,7.335132,1000,147.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.249039,29.808675,300.057714
10,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_3,1,161.870,7.585190,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.226727,29.808648,300.035375
11,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_4,1,164.228,7.469405,1000,149.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.233936,29.782317,300.016253
12,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_5,1,164.665,7.757885,1000,151.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.229392,29.840811,300.070203
13,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_6,1,163.101,7.694206,1000,152.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.246953,29.890160,300.137113
14,FlexibleJobShopFullStochNoTard_2025-06-15_11-4...,FlexibleJobShopFullStochNoTard,sim_last_7,1,164.858,7.716724,1000,150.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.239885,29.770039,300.009924

# Summary statistics

In [8]:
numeric_cols = [
    "mean",
    "DCOP_objective",
]
custom_simh_order = [f"sim_last_{i + 1}" for i in range(8)]

def get_problem_name_from_file_name(file_name):
    """Extract the problem name from the file name."""
    first_part = file_name.split("_")[0]
    if "FullStochNoTard" in first_part:
        return first_part.replace("FullStochNoTard", "")
    elif "FullStoch" in first_part:
        return first_part.replace("FullStoch", "")
    elif "NoTard" in first_part:
        return first_part.replace("NoTard", "")
    else:
        return first_part

# Create a dictionary to hold the summaries for each problem
summaries_dfs = {}
for exp_group, dfs_exp_group in dfs.items():
    for file_name, df in dfs_exp_group.items():

        # Convert numeric columns to proper types (in case they were strings)
        df[numeric_cols] = df[numeric_cols].apply(
            pd.to_numeric,
            errors="coerce"
        )

        # Group by simheuristic and take the mean of selected columns
        summary = (
            df.groupby("simheuristic")[numeric_cols]
            .mean()
            .round(2)
            .reindex(custom_simh_order)
        )

        # Store the summary in a dictionary
        problem_name = get_problem_name_from_file_name(file_name)
        if problem_name not in summaries_dfs:
            summaries_dfs[problem_name] = {}
        summaries_dfs[problem_name][exp_group] = summary

# Create a dictionary to hold concatenated summaries with MultiIndex columns
combined_summaries = {}

for problem_name, exp_group_summaries in summaries_dfs.items():
    dfs_to_concat = []

    for exp_group, df_summary in exp_group_summaries.items():
        # Create a MultiIndex for the columns: (exp_group, column_name)
        df_summary.columns = pd.MultiIndex.from_product(
            [[exp_group], df_summary.columns]
        )
        dfs_to_concat.append(df_summary)

    # Concatenate along columns (axis=1)
    combined_summary = pd.concat(dfs_to_concat, axis=1)

    combined_summaries[problem_name] = combined_summary
    # display(combined_summary)

# Significance testing

In [9]:
from scipy.stats import ttest_rel

# Your significance level
alpha = 0.05

# Find Sidak corrected (cor) significance level
n_tests = 3
alpha_cor = 1 - (1 - alpha) ** (1 / n_tests)

# Find dict tha for each methods gives the signific. outperformed methods
method_significant_better_than = {}
best_method_percentage = {}
for exp_group, dfs_exp_group in dfs.items():
    method_significant_better_than[exp_group] = {}
    best_method_percentage[exp_group] = {}
    for file_name, df in dfs_exp_group.items():
        problem_name = get_problem_name_from_file_name(file_name)
        method_significant_better_than[exp_group][problem_name] = {}
        best_method_percentage[exp_group][problem_name] = {}
        for metric in ["mean", "DCOP_objective"]:
            # Prepare data
            pivot = df.pivot(index="seed", columns="simheuristic", values=metric)
            methods = pivot.columns
            results = pd.DataFrame(index=methods, columns=methods)
        
            # Pairwise t-tests
            df_means = summaries_dfs[problem_name][exp_group][(exp_group, metric)]
            method_significant_better_than[exp_group][problem_name][metric] = {m: [] for m in methods}
            for idx, m1 in enumerate(custom_simh_order):
                for m2 in custom_simh_order[idx + 1:]:
                    stat, p = ttest_rel(pivot[m1], pivot[m2])
                    if p < alpha_cor:
                        # m1 and m2 results are significantly different
                        if df_means.loc[m1] < df_means.loc[m2]:
                            method_significant_better_than[exp_group][problem_name][metric][m1].append(m2)    
                        else:
                            method_significant_better_than[exp_group][problem_name][metric][m2].append(m1)
                            
            # Check how often each method is best over all seeds
            best_method_percentage[exp_group][problem_name][metric] = {m: 0 for m in methods}
            num_exps = len(pivot.index)
            for seed in pivot.index:
                min_value = pivot.loc[seed].min()  # Get the minimum value for this seed
                best_methods = pivot.loc[seed][pivot.loc[seed] == min_value].index  # Get all methods with the minimum value
                for best_method in best_methods:
                    best_method_percentage[exp_group][problem_name][metric][best_method] += 100 * 1 / num_exps
# print(exp_group)
# print(method_significant_better_than[exp_group])
# print(pivot)
# print(best_method_counter[exp_group][problem_name][metric])

# Latex table

In [10]:
# Mapping for better LaTeX names
label_opt_approach = "\\textbf{Optimization approach}"
label_mean_objective = "\\textbf{Mean objective}"
label_objective = "\\textbf{Objective}"
label_problem = "\\textbf{Problem}"
latex_name_mapping = {
    "mean": label_mean_objective,
    "DCOP_objective": label_objective,
    "sim_last_1": "Simulate-last heuristic 1",
    "sim_last_2": "Simulate-last heuristic 2",
    "sim_last_3": "Simulate-last heuristic 3",
    "sim_last_4": "Simulate-last heuristic 4",
    "sim_last_5": "Simulate-last heuristic 5",
    "sim_last_6": "Simulate-last heuristic 6",
    "sim_last_7": "Simulate-last heuristic 7",
    "sim_last_8": "Simulate-last heuristic 8",
    "dyn_simh": "Dynamic simheuristic",
    "sim_last": "Simulate-last heuristic",
    "std_simh": "Standard simheuristic",
    "simheuristic": label_opt_approach,
    "FlexibleJobShop": "FJS",
    "HybridFlowShop": "HFS",
    "JobShop": "JS",
    "ParallelMachines": "PM",
    "OpenShop": "OS",
    "p = 0.3": "\\underline{\\textbf{30\\% of durations random}}",
    "p = 1.0": "\\underline{\\textbf{All durations random}}",
    # Add more mappings as needed
    }

# Merge all problem dataframes and add a 'Problem' column
merged_df_list = []
for problem_name, combined_df in combined_summaries.items():
    # Add a column for the problem name
    combined_df[label_problem] = problem_name
    merged_df_list.append(combined_df)

# Concatenate all dataframes into a single one
df_merged = pd.concat(merged_df_list)
df_merged.reset_index(inplace=True)

# Now apply transformations on the merged dataframe
df_latex = df_merged.copy()

# Rename columns (first and second level)
df_latex.columns = pd.MultiIndex.from_tuples([
    (
        latex_name_mapping.get(exp_group, exp_group),   # First level
        latex_name_mapping.get(metric, metric)          # Second level
        )
    for exp_group, metric in df_latex.columns
    ])

# Create MultiIndex
df_latex.set_index([label_problem, label_opt_approach], inplace=True)

# Rename rows (index) using the latex_name_mapping dictionary
df_latex.index = df_latex.index.set_levels([
    df_latex.index.levels[0].map(lambda x: latex_name_mapping.get(x, x)),  # Rename 'Problem' index
    df_latex.index.levels[1].map(lambda x: latex_name_mapping.get(x, x))   # Rename 'Optimization approach' index
    ])

# Rename index names as well
df_latex.index.names = [latex_name_mapping.get(name, name) for name in df_latex.index.names]

# Bold best (lowest) values in each column within each problem
for metric in df_latex.columns:
    df_latex[metric] = df_latex.groupby(level=0)[[metric]].transform(
        lambda group: [
            f"\\textbf{{{val:.2f}}}" if val == group.min() else f"{val:.2f}"
            for val in group
            ]
        )

# Add superscripts for methods that are significantly better
roman_numerals = ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"]
numerals = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
assert len(roman_numerals) >= len(custom_simh_order)
method_symbols = {
    simh_name: numerals[idx]
    for idx, simh_name in enumerate(custom_simh_order)
    }
inverse_latex_mapping = {v: k for k, v in latex_name_mapping.items()}
for (exp_group, metric) in df_latex.columns:
    for (problem, method) in df_latex.index:
        # Get LaTeX-formatted value (already may contain \textbf{})
        value = df_latex.loc[(problem, method), (exp_group, metric)]

        # Reverse map to original keys
        raw_problem = inverse_latex_mapping[problem]
        raw_method = inverse_latex_mapping[method]
        raw_exp_group = inverse_latex_mapping[exp_group]
        raw_metric = inverse_latex_mapping[metric]

        # Get list of worse methods
        worse_methods = method_significant_better_than[raw_exp_group][raw_problem][raw_metric][raw_method]
        if len(worse_methods) > 0:
            # Add superscript
            symbols = ",".join(method_symbols[m] for m in worse_methods)
            value = value + "$^{(" + symbols + ")}$"
            df_latex.loc[(problem, method), (exp_group, metric)] = value
                
        # Add percentage how often the best
        perc = best_method_percentage[raw_exp_group][raw_problem][raw_metric][raw_method]
        if value.endswith("}$"):
            value = value[:-1]
            value = value + "_{" + f"({perc:.0f}\\%)" + "}$"
        else:
            value = value + "$_{" + f"({perc:.0f}\\%)" + "}$"
        df_latex.loc[(problem, method), (exp_group, metric)] = value
        
# Export to LaTeX for the merged table
if b_with_tardiness:
    caption = "Summary results parameter tuning simulate-last heuristic for all problems with tardiness objective."
    label = "tab:param_tuning_sim_last_all_problems_with_tardiness"
else:
    caption = "Summary results parameter tuning simulate-last heuristic for all problems without tardiness objective."
    label = "tab:param_tuning_sim_last_all_problems_without_tardiness"
caption += " Best values marked in \\textbf{bold}. If a method is significantly better than others, it is marked with superscript in parentheses: "
# markings = ', '.join('$' + method_symbols[simh_name] + '$' + " - " + latex_name_mapping[simh_name].lower() for simh_name in custom_simh_order) 
markings = '$i$ stands for simulate-last heuristic $i$'
caption += markings + '.'
caption += ' The percentage in parentheses indicates how often the method was the best across all seeds.'

# Export the LaTeX table
latex_table = df_latex.to_latex(
    index=True,
    multirow=True,
    multicolumn=True,
    multicolumn_format='c',
    escape=False,
    caption=caption,
    column_format='ll|cc|cc',
    label=label
    )

# Correctly center the table
latex_table = latex_table.replace("\\begin{table}", "\\begin{table}[ht!]\n\\centering")
latex_table = latex_table.replace("\multicolumn{2}{c}", "\multicolumn{2}{c|}", 1)

# Manual string replacement for multirow and optimization approaches
old_part = f" &  & {label_mean_objective}"
new_part = f"{label_problem} & {label_opt_approach} & {label_mean_objective}"
latex_table = latex_table.replace(old_part, new_part, 1)
remove_part = f"{label_problem} & {label_opt_approach} &  &  &  &  \\\\\n"
latex_table = latex_table.replace(remove_part, "", 1)

# Remove the extra line at the end of the table
latex_table = latex_table.replace("\\cline{1-6}\n\\bottomrule", "\\bottomrule")

# # Print final LaTeX code
# print(f"% === LaTeX table for all problems ===")
# print(latex_table)
print(df_latex)
print(caption) 

# Save to .tex file
if b_with_tardiness:
    tex_name = "param_tuning_sim_last_with_tardiness"
else:
    tex_name = "param_tuning_sim_last_without_tardiness"
with open(f"latex/{tex_name}.tex", "w") as f:
    f.write(latex_table)
    print(f"Latex table saved to latex/{tex_name}.tex")

                                                \underline{\textbf{30\% of durations random}}  \
                                                                      \textbf{Mean objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Simulate-last heuristic 1                                 8365.11$_{(15\%)}$
                 Simulate-last heuristic 2                         8299.52$^{(7,8)}_{(20\%)}$
                 Simulate-last heuristic 3                                 8325.88$_{(15\%)}$
                 Simulate-last heuristic 4                  \textbf{8292.31}$^{(8)}_{(20\%)}$
                 Simulate-last heuristic 5                                 8344.68$_{(10\%)}$
                 Simulate-last heuristic 6                                 8335.31$_{(15\%)}$
                 Simulate-last heuristic 7                                  8378.01$_{(0\%)}$
                 Simulate-last heuristic 8                                  8442.16$_{(5\%)}$
PM               Simulate-last heuristic 1                                   76.81$_{(10\%)}$
                 Simulate-last heuristic 2                                   77.22$_{(15\%)}$
                 Simulate-last heuristic 3                                   77.62$_{(10\%)}$
                 Simulate-last heuristic 4                                    79.15$_{(5\%)}$
                 Simulate-last heuristic 5                                   78.86$_{(20\%)}$
                 Simulate-last heuristic 6                                   77.46$_{(15\%)}$
                 Simulate-last heuristic 7                                   76.66$_{(15\%)}$
                 Simulate-last heuristic 8                          \textbf{76.61}$_{(10\%)}$
HFS              Simulate-last heuristic 1                                  156.95$_{(15\%)}$
                 Simulate-last heuristic 2                                   157.38$_{(5\%)}$
                 Simulate-last heuristic 3                                  156.79$_{(15\%)}$
                 Simulate-last heuristic 4                                  157.13$_{(10\%)}$
                 Simulate-last heuristic 5                 \textbf{156.48}$^{(2,4)}_{(25\%)}$
                 Simulate-last heuristic 6                            156.64$^{(2)}_{(10\%)}$
                 Simulate-last heuristic 7                                   156.97$_{(5\%)}$
                 Simulate-last heuristic 8                                  157.11$_{(15\%)}$
JS               Simulate-last heuristic 1                                12331.55$_{(20\%)}$
                 Simulate-last heuristic 2                                12357.12$_{(15\%)}$
                 Simulate-last heuristic 3               \textbf{12304.70}$^{(7,8)}_{(25\%)}$
                 Simulate-last heuristic 4                      12312.12$^{(5,7,8)}_{(20\%)}$
                 Simulate-last heuristic 5                                12411.38$_{(10\%)}$
                 Simulate-last heuristic 6                                 12369.55$_{(5\%)}$
                 Simulate-last heuristic 7                                 12402.99$_{(5\%)}$
                 Simulate-last heuristic 8                                 12399.46$_{(0\%)}$
FJS              Simulate-last heuristic 1                                  151.02$_{(15\%)}$
                 Simulate-last heuristic 2                                   151.43$_{(5\%)}$
                 Simulate-last heuristic 3                                  150.41$_{(15\%)}$
                 Simulate-last heuristic 4                   \textbf{150.11}$^{(7)}_{(30\%)}$
                 Simulate-last heuristic 5                            150.22$^{(7)}_{(20\%)}$
                 Simulate-last heuristic 6                             150.14$^{(7)}_{(5\%)}$
                 Simulate-last heuristic 7                                   151.83$_{(5\%)}$
                 Simulate-last heuristic 8                                   151.18$_{(5\%)}$

                                                                                               \
                                                                           \textbf{Objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Simulate-last heuristic 1                     7857.45$^{(5,6,7,8)}_{(25\%)}$
                 Simulate-last heuristic 2          \textbf{7791.05}$^{(3,5,6,7,8)}_{(55\%)}$
                 Simulate-last heuristic 3                     7893.35$^{(5,6,7,8)}_{(10\%)}$
                 Simulate-last heuristic 4                     7865.15$^{(5,6,7,8)}_{(10\%)}$
                 Simulate-last heuristic 5                          7989.70$^{(7,8)}_{(0\%)}$
                 Simulate-last heuristic 6                          7988.10$^{(7,8)}_{(0\%)}$
                 Simulate-last heuristic 7                                  8090.95$_{(0\%)}$
                 Simulate-last heuristic 8                                  8169.50$_{(0\%)}$
PM               Simulate-last heuristic 1                          \textbf{73.55}$_{(25\%)}$
                 Simulate-last heuristic 2                                   73.95$_{(25\%)}$
                 Simulate-last heuristic 3                                   75.15$_{(15\%)}$
                 Simulate-last heuristic 4                                   76.50$_{(15\%)}$
                 Simulate-last heuristic 5                                   76.95$_{(20\%)}$
                 Simulate-last heuristic 6                                   75.40$_{(20\%)}$
                 Simulate-last heuristic 7                                   75.25$_{(10\%)}$
                 Simulate-last heuristic 8                                   75.20$_{(10\%)}$
HFS              Simulate-last heuristic 1         \textbf{145.70}$^{(3,4,5,6,7,8)}_{(80\%)}$
                 Simulate-last heuristic 2                  145.85$^{(3,4,5,6,7,8)}_{(60\%)}$
                 Simulate-last heuristic 3                       147.85$^{(5,6,7,8)}_{(5\%)}$
                 Simulate-last heuristic 4                       147.85$^{(5,6,7,8)}_{(0\%)}$
                 Simulate-last heuristic 5                           149.40$^{(7,8)}_{(0\%)}$
                 Simulate-last heuristic 6                           149.20$^{(7,8)}_{(0\%)}$
                 Simulate-last heuristic 7                                   150.95$_{(0\%)}$
                 Simulate-last heuristic 8                                   151.45$_{(0\%)}$
JS               Simulate-last heuristic 1       \textbf{11835.30}$^{(3,4,5,6,7,8)}_{(45\%)}$
                 Simulate-last heuristic 2                    11872.30$^{(5,6,7,8)}_{(25\%)}$
                 Simulate-last heuristic 3                    11908.80$^{(5,6,7,8)}_{(15\%)}$
                 Simulate-last heuristic 4                    11903.65$^{(5,6,7,8)}_{(10\%)}$
                 Simulate-last heuristic 5                                 12061.45$_{(5\%)}$
                 Simulate-last heuristic 6                           12044.55$^{(8)}_{(0\%)}$
                 Simulate-last heuristic 7                                 12137.65$_{(0\%)}$
                 Simulate-last heuristic 8                                 12139.50$_{(0\%)}$
FJS              Simulate-last heuristic 1             \textbf{142.85}$^{(5,6,7,8)}_{(45\%)}$
                 Simulate-last heuristic 2                      143.30$^{(5,6,7,8)}_{(30\%)}$
                 Simulate-last heuristic 3                      142.95$^{(5,6,7,8)}_{(45\%)}$
                 Simulate-last heuristic 4                      142.90$^{(5,6,7,8)}_{(50\%)}$
                 Simulate-last heuristic 5                          145.50$^{(7,8)}_{(15\%)}$
                 Simulate-last heuristic 6                           145.35$^{(7,8)}_{(0\%)}$
                 Simulate-last heuristic 7                                   148.60$_{(0\%)}$
                 Simulate-last heuristic 8                                   147.85$_{(0\%)}$

                                                \underline{\textbf{All durations random}}  \
                                                                  \textbf{Mean objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Simulate-last heuristic 1                             8911.44$_{(15\%)}$
                 Simulate-last heuristic 2                             8937.40$_{(25\%)}$
                 Simulate-last heuristic 3                             8935.66$_{(10\%)}$
                 Simulate-last heuristic 4                     \textbf{8906.57}$_{(5\%)}$
                 Simulate-last heuristic 5                             8942.61$_{(10\%)}$
                 Simulate-last heuristic 6                             8918.32$_{(15\%)}$
                 Simulate-last heuristic 7                             8924.69$_{(10\%)}$
                 Simulate-last heuristic 8                             8926.55$_{(10\%)}$
PM               Simulate-last heuristic 1                                80.29$_{(5\%)}$
                 Simulate-last heuristic 2                               80.18$_{(10\%)}$
                 Simulate-last heuristic 3                               81.28$_{(10\%)}$
                 Simulate-last heuristic 4                               82.03$_{(10\%)}$
                 Simulate-last heuristic 5                               81.14$_{(15\%)}$
                 Simulate-last heuristic 6                      \textbf{79.39}$_{(20\%)}$
                 Simulate-last heuristic 7                               80.02$_{(20\%)}$
                 Simulate-last heuristic 8                               80.79$_{(10\%)}$
HFS              Simulate-last heuristic 1                               167.44$_{(5\%)}$
                 Simulate-last heuristic 2                               167.71$_{(0\%)}$
                 Simulate-last heuristic 3                               167.86$_{(0\%)}$
                 Simulate-last heuristic 4                               167.57$_{(5\%)}$
                 Simulate-last heuristic 5                    167.03$^{(2,3,4)}_{(25\%)}$
                 Simulate-last heuristic 6             \textbf{166.94}$^{(2,3)}_{(25\%)}$
                 Simulate-last heuristic 7                              167.53$_{(15\%)}$
                 Simulate-last heuristic 8                              167.25$_{(25\%)}$
JS               Simulate-last heuristic 1                   \textbf{12902.76}$_{(10\%)}$
                 Simulate-last heuristic 2                            12918.16$_{(30\%)}$
                 Simulate-last heuristic 3                            12929.25$_{(20\%)}$
                 Simulate-last heuristic 4                            12979.67$_{(10\%)}$
                 Simulate-last heuristic 5                            12948.58$_{(15\%)}$
                 Simulate-last heuristic 6                            12956.02$_{(10\%)}$
                 Simulate-last heuristic 7                             12951.42$_{(0\%)}$
                 Simulate-last heuristic 8                             12946.43$_{(5\%)}$
FJS              Simulate-last heuristic 1                              159.16$_{(20\%)}$
                 Simulate-last heuristic 2                              158.82$_{(10\%)}$
                 Simulate-last heuristic 3                     \textbf{158.44}$_{(20\%)}$
                 Simulate-last heuristic 4                               159.26$_{(5\%)}$
                 Simulate-last heuristic 5                               159.50$_{(0\%)}$
                 Simulate-last heuristic 6                              159.30$_{(20\%)}$
                 Simulate-last heuristic 7                              159.48$_{(15\%)}$
                 Simulate-last heuristic 8                              159.35$_{(10\%)}$


                                                                           \textbf{Objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Simulate-last heuristic 1        \textbf{7805.10}$^{(3,4,5,6,7,8)}_{(50\%)}$
                 Simulate-last heuristic 2                                 7857.30$_{(35\%)}$
                 Simulate-last heuristic 3                                  7920.65$_{(5\%)}$
                 Simulate-last heuristic 4                                  7884.45$_{(0\%)}$
                 Simulate-last heuristic 5                                  7918.40$_{(5\%)}$
                 Simulate-last heuristic 6                                  7915.30$_{(5\%)}$
                 Simulate-last heuristic 7                                  7938.70$_{(0\%)}$
                 Simulate-last heuristic 8                                  7942.60$_{(0\%)}$
PM               Simulate-last heuristic 1                                   74.05$_{(15\%)}$
                 Simulate-last heuristic 2                                   73.95$_{(15\%)}$
                 Simulate-last heuristic 3                                   75.65$_{(10\%)}$
                 Simulate-last heuristic 4                                   76.70$_{(10\%)}$
                 Simulate-last heuristic 5                                   75.75$_{(20\%)}$
                 Simulate-last heuristic 6                          \textbf{73.85}$_{(20\%)}$
                 Simulate-last heuristic 7                                   74.70$_{(20\%)}$
                 Simulate-last heuristic 8                                   75.30$_{(10\%)}$
HFS              Simulate-last heuristic 1         \textbf{145.95}$^{(3,4,5,6,7,8)}_{(65\%)}$
                 Simulate-last heuristic 2                      146.20$^{(3,4,7,8)}_{(65\%)}$
                 Simulate-last heuristic 3                                   147.70$_{(5\%)}$
                 Simulate-last heuristic 4                                  147.55$_{(10\%)}$
                 Simulate-last heuristic 5                                   147.15$_{(0\%)}$
                 Simulate-last heuristic 6                                  147.00$_{(10\%)}$
                 Simulate-last heuristic 7                                   147.60$_{(0\%)}$
                 Simulate-last heuristic 8                                  147.60$_{(10\%)}$
JS               Simulate-last heuristic 1       \textbf{11820.80}$^{(3,4,5,6,7,8)}_{(20\%)}$
                 Simulate-last heuristic 2                          11849.00$^{(7)}_{(35\%)}$
                 Simulate-last heuristic 3                                11885.95$_{(15\%)}$
                 Simulate-last heuristic 4                                 11935.20$_{(5\%)}$
                 Simulate-last heuristic 5                                11915.05$_{(15\%)}$
                 Simulate-last heuristic 6                                 11932.20$_{(5\%)}$
                 Simulate-last heuristic 7                                 11925.25$_{(0\%)}$
                 Simulate-last heuristic 8                                 11924.80$_{(5\%)}$
FJS              Simulate-last heuristic 1                    143.20$^{(4,5,6,7,8)}_{(35\%)}$
                 Simulate-last heuristic 2         \textbf{142.60}$^{(3,4,5,6,7,8)}_{(65\%)}$
                 Simulate-last heuristic 3                            143.80$^{(8)}_{(20\%)}$
                 Simulate-last heuristic 4                                  144.35$_{(10\%)}$
                 Simulate-last heuristic 5                                   145.00$_{(0\%)}$
                 Simulate-last heuristic 6                                   145.35$_{(0\%)}$
                 Simulate-last heuristic 7                                  145.00$_{(15\%)}$
                 Simulate-last heuristic 8                                   145.00$_{(5\%)}$
Summary results parameter tuning simulate-last heuristic for all problems without tardiness objective. Best values marked in \textbf{bold}. If a method is significantly better than others, it is marked with superscript in parentheses: $i$ stands for simulate-last heuristic $i$. The percentage in parentheses indicates how often the method was the best across all seeds.
Latex table saved to latex/param_tuning_sim_last_without_tardiness.tex