# Parameter tuning for dynamic simheuristic.

This notebook loads the results of different dynamic simheuristics (with longer CP-SAT solve time) applied to various scheduling problems,
performs summary statistics, and conducts significance testing on the results. It generates a LaTeX table summarizing the findings to be reported in the article.

Instructions:

- Run cells below with b_with_tardiness set to True or False to compare results with and without tardiness in the objective function.
- It will save .tex file with the results table in the `latex` directory.
- Copy the generated .tex files to Overleaf results folder.

In [1]:
from pathlib import Path

import pandas as pd

# Data loading

In [7]:
b_with_tardiness = True

DATA_DIR = Path("../results")
all_csv_files = """HybridFlowShopFullStochNoTard_2025-07-05_18-08-27.csv
OpenShopNoTard_2025-07-05_18-07-28.csv
HybridFlowShopFullStoch_2025-07-05_18-08-01.csv
OpenShop_2025-07-05_18-07-04.csv
FlexibleJobShopFullStochNoTard_2025-07-05_18-07-43.csv
JobShopFullStochNoTard_2025-07-05_18-08-43.csv
JobShopFullStoch_2025-07-05_18-08-24.csv
JobShopNoTard_2025-07-05_18-08-24.csv
FlexibleJobShopFullStoch_2025-07-05_18-07-44.csv
JobShop_2025-07-05_18-08-21.csv
FlexibleJobShop_2025-07-05_18-07-25.csv
FlexibleJobShopNoTard_2025-07-05_18-07-47.csv
ParallelMachinesFullStochNoTard_2025-07-05_18-08-50.csv
ParallelMachines_2025-07-05_18-08-44.csv
HybridFlowShop_2025-07-05_18-07-56.csv
ParallelMachinesFullStoch_2025-07-05_18-08-41.csv
ParallelMachinesNoTard_2025-07-05_18-08-43.csv
HybridFlowShopNoTard_2025-07-05_18-08-09.csv
OpenShopFullStoch_2025-07-05_18-07-21.csv
OpenShopFullStochNoTard_2025-07-05_18-07-22.csv""".split('\n')
problem_order = ['OpenShop', 'ParallelMachines', 'HybridFlowShop', 'JobShop', 'FlexibleJobShop']
def find_with_part(file_names, part):
    """Find all file names that contain a specific part."""
    return [name for name in file_names if part == name.split('_')[0]][0]

if b_with_tardiness:
    file_names_per_exp_group = {
        "p = 0.3": [
            find_with_part(all_csv_files, problem_name)                
            for problem_name in problem_order
            ],
        "p = 1.0": [
            find_with_part(all_csv_files, problem_name + "FullStoch")
            for problem_name in problem_order
            ],
        }  # the key denotes a group of experiments
else:
    file_names_per_exp_group = {
        "p = 0.3":[
            find_with_part(all_csv_files, problem_name + "NoTard")
            for problem_name in problem_order
            ],
        "p = 1.0": [
            find_with_part(all_csv_files, problem_name + "FullStochNoTard")
            for problem_name in problem_order
            ],
        }  # without tardiness
print(file_names_per_exp_group)
dfs = {}
for exp_group, file_names in file_names_per_exp_group.items():
    dfs[exp_group] = {}
    for file_name in file_names:
        dfs[exp_group][file_name] = pd.read_csv(DATA_DIR / file_name)
        display(dfs[exp_group][file_name].head(5))

{'p = 0.3': ['OpenShop_2025-07-05_18-07-04.csv', 'ParallelMachines_2025-07-05_18-08-44.csv', 'HybridFlowShop_2025-07-05_18-07-56.csv', 'JobShop_2025-07-05_18-08-21.csv', 'FlexibleJobShop_2025-07-05_18-07-25.csv'], 'p = 1.0': ['OpenShopFullStoch_2025-07-05_18-07-21.csv', 'ParallelMachinesFullStoch_2025-07-05_18-08-41.csv', 'HybridFlowShopFullStoch_2025-07-05_18-08-01.csv', 'JobShopFullStoch_2025-07-05_18-08-24.csv', 'FlexibleJobShopFullStoch_2025-07-05_18-07-44.csv']}

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,OpenShop_2025-07-05_18-07-04,OpenShop,dyn_simh_1,0,9005.066,2190.778329,1000,7392.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.384901,14.655473,300.040374
1,OpenShop_2025-07-05_18-07-04,OpenShop,dyn_simh_2,0,8291.235,1452.499619,1000,7465.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.059343,29.993194,300.052536
2,OpenShop_2025-07-05_18-07-04,OpenShop,dyn_simh_3,0,8543.653,1929.292885,1000,7304.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.142504,14.860146,300.002650
3,OpenShop_2025-07-05_18-07-04,OpenShop,dyn_simh_4,0,8536.720,1333.559583,1000,7728.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.049227,30.008633,300.057860
4,OpenShop_2025-07-05_18-07-04,OpenShop,dyn_simh_1,1,9910.753,2404.334715,1000,7794.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.134063,14.889017,300.023080

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,ParallelMachines_2025-07-05_18-08-44,ParallelMachines,dyn_simh_1,0,58.817,3.498787,1000,58.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,285.396275,14.634817,300.031092
1,ParallelMachines_2025-07-05_18-08-44,ParallelMachines,dyn_simh_2,0,97.411,124.133187,1000,62.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.419309,29.603315,300.022624
2,ParallelMachines_2025-07-05_18-08-44,ParallelMachines,dyn_simh_3,0,79.713,85.261988,1000,59.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,285.337094,14.723019,300.060113
3,ParallelMachines_2025-07-05_18-08-44,ParallelMachines,dyn_simh_4,0,69.080,6.983523,1000,68.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.434049,29.613145,300.047194
4,ParallelMachines_2025-07-05_18-08-44,ParallelMachines,dyn_simh_1,1,71.579,26.714374,1000,66.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,285.479613,14.537614,300.017226

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,HybridFlowShop_2025-07-05_18-07-56,HybridFlowShop,dyn_simh_1,0,164.218,77.413865,1000,132.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.187572,14.884865,300.072438
1,HybridFlowShop_2025-07-05_18-07-56,HybridFlowShop,dyn_simh_2,0,159.139,71.046152,1000,140.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.231679,29.828335,300.060014
2,HybridFlowShop_2025-07-05_18-07-56,HybridFlowShop,dyn_simh_3,0,174.453,22.855673,1000,166.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.208932,14.830982,300.039914
3,HybridFlowShop_2025-07-05_18-07-56,HybridFlowShop,dyn_simh_4,0,172.505,111.515012,1000,135.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.137611,29.934210,300.071822
4,HybridFlowShop_2025-07-05_18-07-56,HybridFlowShop,dyn_simh_1,1,301.456,231.911039,1000,138.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.133999,14.942002,300.076001

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,JobShop_2025-07-05_18-08-21,JobShop,dyn_simh_1,0,23107.609,9169.148484,1000,14813.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.057245,14.973732,300.030977
1,JobShop_2025-07-05_18-08-21,JobShop,dyn_simh_2,0,24012.968,11465.441824,1000,12906.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.063935,30.012601,300.076535
2,JobShop_2025-07-05_18-08-21,JobShop,dyn_simh_3,0,26105.203,9830.690520,1000,17838.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.212689,14.844143,300.056832
3,JobShop_2025-07-05_18-08-21,JobShop,dyn_simh_4,0,23713.243,13669.852560,1000,12802.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.393119,29.633127,300.026246
4,JobShop_2025-07-05_18-08-21,JobShop,dyn_simh_1,1,27275.811,9724.100727,1000,15648.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.056195,15.022717,300.078912

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,FlexibleJobShop_2025-07-05_18-07-25,FlexibleJobShop,dyn_simh_1,0,1710.782,1873.020630,1000,305.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.157745,14.898812,300.056556
1,FlexibleJobShop_2025-07-05_18-07-25,FlexibleJobShop,dyn_simh_2,0,4777.793,2423.769286,1000,2408.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.224185,29.875730,300.099914
2,FlexibleJobShop_2025-07-05_18-07-25,FlexibleJobShop,dyn_simh_3,0,1557.462,1289.687132,1000,712.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.148328,14.890670,300.038998
3,FlexibleJobShop_2025-07-05_18-07-25,FlexibleJobShop,dyn_simh_4,0,1927.131,1636.627498,1000,807.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,271.634638,28.372374,300.007012
4,FlexibleJobShop_2025-07-05_18-07-25,FlexibleJobShop,dyn_simh_1,1,2798.223,2945.711722,1000,330.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.136792,14.916592,300.053384

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,OpenShopFullStoch_2025-07-05_18-07-21,OpenShopFullStoch,dyn_simh_1,0,13830.690,5454.441127,1000,8297.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.134884,14.905737,300.040621
1,OpenShopFullStoch_2025-07-05_18-07-21,OpenShopFullStoch,dyn_simh_2,0,13830.690,5454.441127,1000,8297.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.050999,29.984382,300.035381
2,OpenShopFullStoch_2025-07-05_18-07-21,OpenShopFullStoch,dyn_simh_3,0,13722.800,5310.395623,1000,8287.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.047550,14.955978,300.003529
3,OpenShopFullStoch_2025-07-05_18-07-21,OpenShopFullStoch,dyn_simh_4,0,13974.085,5634.577508,1000,8301.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,270.209477,29.898031,300.107508
4,OpenShopFullStoch_2025-07-05_18-07-21,OpenShopFullStoch,dyn_simh_1,1,12283.767,3213.824681,1000,8652.0,"{""tasks"": [{""mode"": 0, ""resources"": [0, 5], ""s...",\nCallback Log:\n-----------------------------...,Feasible,285.133330,15.016289,300.149619

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,ParallelMachinesFullStoch_2025-07-05_18-08-41,ParallelMachinesFullStoch,dyn_simh_1,0,197.696,257.011902,1000,55.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,285.388063,14.670567,300.058630
1,ParallelMachinesFullStoch_2025-07-05_18-08-41,ParallelMachinesFullStoch,dyn_simh_2,0,246.003,308.469553,1000,54.0,"{""tasks"": [{""mode"": 80, ""resources"": [2], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.337239,29.664810,300.002049
2,ParallelMachinesFullStoch_2025-07-05_18-08-41,ParallelMachinesFullStoch,dyn_simh_3,0,215.458,280.904479,1000,55.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,285.441826,14.574009,300.015835
3,ParallelMachinesFullStoch_2025-07-05_18-08-41,ParallelMachinesFullStoch,dyn_simh_4,0,198.624,244.555995,1000,61.0,"{""tasks"": [{""mode"": 40, ""resources"": [1], ""sta...",\nCallback Log:\n-----------------------------...,Feasible,270.328255,29.726694,300.054949
4,ParallelMachinesFullStoch_2025-07-05_18-08-41,ParallelMachinesFullStoch,dyn_simh_1,1,136.124,169.159654,1000,70.0,"{""tasks"": [{""mode"": 120, ""resources"": [3], ""st...",\nCallback Log:\n-----------------------------...,Feasible,285.330587,14.728131,300.058718

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,HybridFlowShopFullStoch_2025-07-05_18-08-01,HybridFlowShopFullStoch,dyn_simh_1,0,333.259,293.275352,1000,128.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.386380,14.621919,300.008300
1,HybridFlowShopFullStoch_2025-07-05_18-08-01,HybridFlowShopFullStoch,dyn_simh_2,0,336.212,266.378781,1000,133.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.215595,29.822521,300.038116
2,HybridFlowShopFullStoch_2025-07-05_18-08-01,HybridFlowShopFullStoch,dyn_simh_3,0,352.826,289.557003,1000,136.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.141223,14.905017,300.046240
3,HybridFlowShopFullStoch_2025-07-05_18-08-01,HybridFlowShopFullStoch,dyn_simh_4,0,338.768,296.881987,1000,126.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.133716,29.932783,300.066499
4,HybridFlowShopFullStoch_2025-07-05_18-08-01,HybridFlowShopFullStoch,dyn_simh_1,1,383.881,311.180544,1000,148.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.134224,14.903754,300.037978

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,JobShopFullStoch_2025-07-05_18-08-24,JobShopFullStoch,dyn_simh_1,0,53287.208,26113.278096,1000,18196.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.166703,14.894933,300.061635
1,JobShopFullStoch_2025-07-05_18-08-24,JobShopFullStoch,dyn_simh_2,0,50020.521,25333.717092,1000,19866.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.076277,29.984522,300.060799
2,JobShopFullStoch_2025-07-05_18-08-24,JobShopFullStoch,dyn_simh_3,0,56203.970,25914.297458,1000,23391.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.057137,15.077369,300.134506
3,JobShopFullStoch_2025-07-05_18-08-24,JobShopFullStoch,dyn_simh_4,0,57294.228,28078.535382,1000,17963.0,"{""tasks"": [{""mode"": 0, ""resources"": [0], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.085193,29.994700,300.079893
4,JobShopFullStoch_2025-07-05_18-08-24,JobShopFullStoch,dyn_simh_1,1,71707.100,27932.338096,1000,19346.0,"{""tasks"": [{""mode"": 0, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.062879,15.002639,300.065518

,project_name,problem_type,simheuristic,seed,mean,std,num_sims,DCOP_objective,DCOP_solution,callback_log,solve status,solver_phase_dur,final_sim_phase_dur,total_exp_dur
0,FlexibleJobShopFullStoch_2025-07-05_18-07-44,FlexibleJobShopFullStoch,dyn_simh_1,0,27653.939,9029.626317,1000,11615.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.938496,14.085148,300.023645
1,FlexibleJobShopFullStoch_2025-07-05_18-07-44,FlexibleJobShopFullStoch,dyn_simh_2,0,23569.077,7911.220570,1000,10806.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.170364,29.854784,300.025148
2,FlexibleJobShopFullStoch_2025-07-05_18-07-44,FlexibleJobShopFullStoch,dyn_simh_3,0,20805.276,7905.228993,1000,6310.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,286.196200,13.834050,300.030249
3,FlexibleJobShopFullStoch_2025-07-05_18-07-44,FlexibleJobShopFullStoch,dyn_simh_4,0,25056.294,7978.074610,1000,9409.0,"{""tasks"": [{""mode"": 1, ""resources"": [1], ""star...",\nCallback Log:\n-----------------------------...,Feasible,270.153316,29.902470,300.055786
4,FlexibleJobShopFullStoch_2025-07-05_18-07-44,FlexibleJobShopFullStoch,dyn_simh_1,1,15992.237,5948.026606,1000,10622.0,"{""tasks"": [{""mode"": 3, ""resources"": [3], ""star...",\nCallback Log:\n-----------------------------...,Feasible,285.766775,14.283206,300.049980

# Summary statistics

In [3]:
numeric_cols = [
    "mean",
    "DCOP_objective",
]
custom_simh_order = [f"dyn_simh_{i + 1}" for i in range(4)]

def get_problem_name_from_file_name(file_name):
    """Extract the problem name from the file name."""
    first_part = file_name.split("_")[0]
    if "FullStochNoTard" in first_part:
        return first_part.replace("FullStochNoTard", "")
    elif "FullStoch" in first_part:
        return first_part.replace("FullStoch", "")
    elif "NoTard" in first_part:
        return first_part.replace("NoTard", "")
    else:
        return first_part

# Create a dictionary to hold the summaries for each problem
summaries_dfs = {}
for exp_group, dfs_exp_group in dfs.items():
    for file_name, df in dfs_exp_group.items():

        # Convert numeric columns to proper types (in case they were strings)
        df[numeric_cols] = df[numeric_cols].apply(
            pd.to_numeric,
            errors="coerce"
        )

        # Group by simheuristic and take the mean of selected columns
        summary = (
            df.groupby("simheuristic")[numeric_cols]
            .mean()
            .round(2)
            .reindex(custom_simh_order)
        )

        # Store the summary in a dictionary
        problem_name = get_problem_name_from_file_name(file_name)
        if problem_name not in summaries_dfs:
            summaries_dfs[problem_name] = {}
        summaries_dfs[problem_name][exp_group] = summary

# Create a dictionary to hold concatenated summaries with MultiIndex columns
combined_summaries = {}

for problem_name, exp_group_summaries in summaries_dfs.items():
    dfs_to_concat = []

    for exp_group, df_summary in exp_group_summaries.items():
        # Create a MultiIndex for the columns: (exp_group, column_name)
        df_summary.columns = pd.MultiIndex.from_product(
            [[exp_group], df_summary.columns]
        )
        dfs_to_concat.append(df_summary)

    # Concatenate along columns (axis=1)
    combined_summary = pd.concat(dfs_to_concat, axis=1)

    combined_summaries[problem_name] = combined_summary
    # display(combined_summary)

               p = 0.3                  p = 1.0
                  mean DCOP_objective      mean DCOP_objective
simheuristic
dyn_simh_1    10065.51        8026.35  22425.67        9031.40
dyn_simh_2    10383.48        8017.15  23159.91        9305.60
dyn_simh_3    10220.42        8100.45  22399.12        8981.45
dyn_simh_4    10358.25        8063.20  22913.12        9048.15

             p = 0.3                p = 1.0
                mean DCOP_objective    mean DCOP_objective
simheuristic
dyn_simh_1    159.44          97.40  316.22         121.85
dyn_simh_2    153.77          84.75  313.69          89.70
dyn_simh_3    147.61          92.95  285.21          74.90
dyn_simh_4    135.76          73.60  317.68          82.30

             p = 0.3                p = 1.0
                mean DCOP_objective    mean DCOP_objective
simheuristic
dyn_simh_1    284.77         142.65  393.89         141.10
dyn_simh_2    274.16         145.45  398.91         143.55
dyn_simh_3    281.41         151.80  407.53         144.50
dyn_simh_4    270.08         141.90  399.91         146.15

               p = 0.3                  p = 1.0
                  mean DCOP_objective      mean DCOP_objective
simheuristic
dyn_simh_1    32363.36       20416.95  75314.33       36279.45
dyn_simh_2    32384.74       20167.20  76467.39       37971.05
dyn_simh_3    32750.34       20590.70  75867.00       37046.45
dyn_simh_4    32460.04       20253.35  76606.01       37259.85

              p = 0.3                  p = 1.0
                 mean DCOP_objective      mean DCOP_objective
simheuristic
dyn_simh_1    7918.97        3693.15  25608.97        8425.70
dyn_simh_2    9504.88        4672.00  24464.96        8675.05
dyn_simh_3    7560.34        3211.50  23869.64        7779.15
dyn_simh_4    8402.60        3980.40  25081.06        8815.45

# Significance testing

In [4]:
from scipy.stats import ttest_rel

# Your significance level
alpha = 0.05

# Find Sidak corrected (cor) significance level
n_tests = 3
alpha_cor = 1 - (1 - alpha) ** (1 / n_tests)

# Find dict tha for each methods gives the signific. outperformed methods
method_significant_better_than = {}
best_method_percentage = {}
for exp_group, dfs_exp_group in dfs.items():
    method_significant_better_than[exp_group] = {}
    best_method_percentage[exp_group] = {}
    for file_name, df in dfs_exp_group.items():
        problem_name = get_problem_name_from_file_name(file_name)
        method_significant_better_than[exp_group][problem_name] = {}
        best_method_percentage[exp_group][problem_name] = {}
        for metric in ["mean", "DCOP_objective"]:
            # Prepare data
            pivot = df.pivot(index="seed", columns="simheuristic", values=metric)
            methods = pivot.columns
            results = pd.DataFrame(index=methods, columns=methods)
        
            # Pairwise t-tests
            df_means = summaries_dfs[problem_name][exp_group][(exp_group, metric)]
            method_significant_better_than[exp_group][problem_name][metric] = {m: [] for m in methods}
            for idx, m1 in enumerate(custom_simh_order):
                for m2 in custom_simh_order[idx + 1:]:
                    stat, p = ttest_rel(pivot[m1], pivot[m2])
                    if p < alpha_cor:
                        # m1 and m2 results are significantly different
                        if df_means.loc[m1] < df_means.loc[m2]:
                            method_significant_better_than[exp_group][problem_name][metric][m1].append(m2)    
                        else:
                            method_significant_better_than[exp_group][problem_name][metric][m2].append(m1)
                            
            # Check how often each method is best over all seeds
            best_method_percentage[exp_group][problem_name][metric] = {m: 0 for m in methods}
            num_exps = len(pivot.index)
            for seed in pivot.index:
                min_value = pivot.loc[seed].min()  # Get the minimum value for this seed
                best_methods = pivot.loc[seed][pivot.loc[seed] == min_value].index  # Get all methods with the minimum value
                for best_method in best_methods:
                    best_method_percentage[exp_group][problem_name][metric][best_method] += 100 * 1 / num_exps
# print(exp_group)
# print(method_significant_better_than[exp_group])
# print(pivot)
# print(best_method_counter[exp_group][problem_name][metric])

# Latex table

In [5]:
# Mapping for better LaTeX names
label_opt_approach = "\\textbf{Optimization approach}"
label_mean_objective = "\\textbf{Mean objective}"
label_objective = "\\textbf{Objective}"
label_problem = "\\textbf{Problem}"
latex_name_mapping = {
    "mean": label_mean_objective,
    "DCOP_objective": label_objective,
    "dyn_simh_1": "Dyn. simh. longer CP-SAT 1",
    "dyn_simh_2": "Dyn. simh. longer CP-SAT 2",
    "dyn_simh_3": "Dyn. simh. longer CP-SAT 3",
    "dyn_simh_4": "Dyn. simh. longer CP-SAT 4",
    "dyn_simh_5": "Dyn. simh. longer CP-SAT 5",
    "dyn_simh_6": "Dyn. simh. longer CP-SAT 6",
    "dyn_simh_7": "Dyn. simh. longer CP-SAT 7",
    "dyn_simh_8": "Dyn. simh. longer CP-SAT 8",
    "dyn_simh": "Dynamic simheuristic",
    "std_simh": "Standard simheuristic",
    "simheuristic": label_opt_approach,
    "FlexibleJobShop": "FJS",
    "HybridFlowShop": "HFS",
    "JobShop": "JS",
    "ParallelMachines": "PM",
    "OpenShop": "OS",
    "p = 0.3": "\\underline{\\textbf{30\\% of durations random}}",
    "p = 1.0": "\\underline{\\textbf{All durations random}}",
    # Add more mappings as needed
    }

# Merge all problem dataframes and add a 'Problem' column
merged_df_list = []
for problem_name, combined_df in combined_summaries.items():
    # Add a column for the problem name
    combined_df[label_problem] = problem_name
    merged_df_list.append(combined_df)

# Concatenate all dataframes into a single one
df_merged = pd.concat(merged_df_list)
df_merged.reset_index(inplace=True)

# Now apply transformations on the merged dataframe
df_latex = df_merged.copy()

# Rename columns (first and second level)
df_latex.columns = pd.MultiIndex.from_tuples([
    (
        latex_name_mapping.get(exp_group, exp_group),   # First level
        latex_name_mapping.get(metric, metric)          # Second level
        )
    for exp_group, metric in df_latex.columns
    ])

# Create MultiIndex
df_latex.set_index([label_problem, label_opt_approach], inplace=True)

# Rename rows (index) using the latex_name_mapping dictionary
df_latex.index = df_latex.index.set_levels([
    df_latex.index.levels[0].map(lambda x: latex_name_mapping.get(x, x)),  # Rename 'Problem' index
    df_latex.index.levels[1].map(lambda x: latex_name_mapping.get(x, x))   # Rename 'Optimization approach' index
    ])

# Rename index names as well
df_latex.index.names = [latex_name_mapping.get(name, name) for name in df_latex.index.names]

# Bold best (lowest) values in each column within each problem
for metric in df_latex.columns:
    df_latex[metric] = df_latex.groupby(level=0)[[metric]].transform(
        lambda group: [
            f"\\textbf{{{val:.2f}}}" if val == group.min() else f"{val:.2f}"
            for val in group
            ]
        )

# Add superscripts for methods that are significantly better
roman_numerals = ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"]
numerals = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10']
assert len(roman_numerals) >= len(custom_simh_order)
method_symbols = {
    simh_name: numerals[idx]
    for idx, simh_name in enumerate(custom_simh_order)
    }
inverse_latex_mapping = {v: k for k, v in latex_name_mapping.items()}
for (exp_group, metric) in df_latex.columns:
    for (problem, method) in df_latex.index:
        # Get LaTeX-formatted value (already may contain \textbf{})
        value = df_latex.loc[(problem, method), (exp_group, metric)]

        # Reverse map to original keys
        raw_problem = inverse_latex_mapping[problem]
        raw_method = inverse_latex_mapping[method]
        raw_exp_group = inverse_latex_mapping[exp_group]
        raw_metric = inverse_latex_mapping[metric]

        # Get list of worse methods
        worse_methods = method_significant_better_than[raw_exp_group][raw_problem][raw_metric][raw_method]
        if len(worse_methods) > 0:
            # Add superscript
            symbols = ",".join(method_symbols[m] for m in worse_methods)
            value = value + "$^{(" + symbols + ")}$"
            df_latex.loc[(problem, method), (exp_group, metric)] = value
                
        # Add percentage how often the best
        perc = best_method_percentage[raw_exp_group][raw_problem][raw_metric][raw_method]
        if value.endswith("}$"):
            value = value[:-1]
            value = value + "_{" + f"({perc:.0f}\\%)" + "}$"
        else:
            value = value + "$_{" + f"({perc:.0f}\\%)" + "}$"
        df_latex.loc[(problem, method), (exp_group, metric)] = value
        
# Export to LaTeX for the merged table
if b_with_tardiness:
    caption = "Summary results parameter tuning dynamic simheuristic (longer CP-SAT time) for all problems with tardiness objective."
    label = "tab:param_tuning_dyn_simh_long_all_problems_with_tardiness"
else:
    caption = "Summary results parameter tuning dynamic simheuristic (longer CP-SAT time) for all problems without tardiness objective."
    label = "tab:param_tuning_dyn_simh_long_all_problems_without_tardiness"
caption += " Best values marked in \\textbf{bold}. If a method is significantly better than others, it is marked with superscript in parentheses: "
# markings = ', '.join('$' + method_symbols[simh_name] + '$' + " - " + latex_name_mapping[simh_name].lower() for simh_name in custom_simh_order) 
markings = '$i$ stands for dynamic simheuristic longer $i$'
caption += markings + '.'
caption += ' The percentage in parentheses indicates how often the method was the best across all seeds.'

# Export the LaTeX table
latex_table = df_latex.to_latex(
    index=True,
    multirow=True,
    multicolumn=True,
    multicolumn_format='c',
    escape=False,
    caption=caption,
    column_format='ll|cc|cc',
    label=label
    )

# Correctly center the table
latex_table = latex_table.replace("\\begin{table}", "\\begin{table}[ht!]\n\\centering")
latex_table = latex_table.replace("\multicolumn{2}{c}", "\multicolumn{2}{c|}", 1)

# Manual string replacement for multirow and optimization approaches
old_part = f" &  & {label_mean_objective}"
new_part = f"{label_problem} & {label_opt_approach} & {label_mean_objective}"
latex_table = latex_table.replace(old_part, new_part, 1)
remove_part = f"{label_problem} & {label_opt_approach} &  &  &  &  \\\\\n"
latex_table = latex_table.replace(remove_part, "", 1)

# Remove the extra line at the end of the table
latex_table = latex_table.replace("\\cline{1-6}\n\\bottomrule", "\\bottomrule")

# # Print final LaTeX code
# print(f"% === LaTeX table for all problems ===")
# print(latex_table)
print(df_latex)
print(caption) 

# Save to .tex file
if b_with_tardiness:
    tex_name = "param_tuning_dyn_simh_long_with_tardiness"
else:
    tex_name = "param_tuning_dyn_simh_long_without_tardiness"
with open(f"latex/{tex_name}.tex", "w") as f:
    f.write(latex_table)
    print(f"Latex table saved to latex/{tex_name}.tex")

                                                \underline{\textbf{30\% of durations random}}  \
                                                                      \textbf{Mean objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Dyn. simh. longer CP-SAT 1                      \textbf{10065.51}$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 2                               10383.48$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 3                               10220.42$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 4                               10358.25$_{(15\%)}$
PM               Dyn. simh. longer CP-SAT 1                                 159.44$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 2                                 153.77$_{(25\%)}$
                 Dyn. simh. longer CP-SAT 3                                 147.61$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 4                        \textbf{135.76}$_{(40\%)}$
HFS              Dyn. simh. longer CP-SAT 1                                 284.77$_{(10\%)}$
                 Dyn. simh. longer CP-SAT 2                                 274.16$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 3                                 281.41$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 4                        \textbf{270.08}$_{(25\%)}$
JS               Dyn. simh. longer CP-SAT 1                      \textbf{32363.36}$_{(25\%)}$
                 Dyn. simh. longer CP-SAT 2                               32384.74$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 3                               32750.34$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 4                               32460.04$_{(25\%)}$
FJS              Dyn. simh. longer CP-SAT 1                          7918.97$^{(2)}_{(20\%)}$
                 Dyn. simh. longer CP-SAT 2                                 9504.88$_{(5\%)}$
                 Dyn. simh. longer CP-SAT 3                 \textbf{7560.34}$^{(2)}_{(50\%)}$
                 Dyn. simh. longer CP-SAT 4                                8402.60$_{(25\%)}$

                                                                               \
                                                           \textbf{Objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Dyn. simh. longer CP-SAT 1                8026.35$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 2       \textbf{8017.15}$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 3                8100.45$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 4                8063.20$_{(30\%)}$
PM               Dyn. simh. longer CP-SAT 1                  97.40$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 2                  84.75$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 3                  92.95$_{(25\%)}$
                 Dyn. simh. longer CP-SAT 4         \textbf{73.60}$_{(30\%)}$
HFS              Dyn. simh. longer CP-SAT 1                 142.65$_{(45\%)}$
                 Dyn. simh. longer CP-SAT 2                 145.45$_{(25\%)}$
                 Dyn. simh. longer CP-SAT 3                 151.80$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 4        \textbf{141.90}$_{(30\%)}$
JS               Dyn. simh. longer CP-SAT 1               20416.95$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 2      \textbf{20167.20}$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 3               20590.70$_{(25\%)}$
                 Dyn. simh. longer CP-SAT 4               20253.35$_{(25\%)}$
FJS              Dyn. simh. longer CP-SAT 1                3693.15$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 2                4672.00$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3       \textbf{3211.50}$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 4                3980.40$_{(20\%)}$

                                                \underline{\textbf{All durations random}}  \
                                                                  \textbf{Mean objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Dyn. simh. longer CP-SAT 1                           22425.67$_{(45\%)}$
                 Dyn. simh. longer CP-SAT 2                           23159.91$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3                  \textbf{22399.12}$_{(45\%)}$
                 Dyn. simh. longer CP-SAT 4                           22913.12$_{(25\%)}$
PM               Dyn. simh. longer CP-SAT 1                             316.22$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 2                             313.69$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3                    \textbf{285.21}$_{(50\%)}$
                 Dyn. simh. longer CP-SAT 4                             317.68$_{(10\%)}$
HFS              Dyn. simh. longer CP-SAT 1                    \textbf{393.89}$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 2                             398.91$_{(40\%)}$
                 Dyn. simh. longer CP-SAT 3                             407.53$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 4                             399.91$_{(25\%)}$
JS               Dyn. simh. longer CP-SAT 1                  \textbf{75314.33}$_{(40\%)}$
                 Dyn. simh. longer CP-SAT 2                           76467.39$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3                           75867.00$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 4                           76606.01$_{(10\%)}$
FJS              Dyn. simh. longer CP-SAT 1                            25608.97$_{(5\%)}$
                 Dyn. simh. longer CP-SAT 2                           24464.96$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 3                  \textbf{23869.64}$_{(60\%)}$
                 Dyn. simh. longer CP-SAT 4                           25081.06$_{(20\%)}$


                                                           \textbf{Objective}
\textbf{Problem} \textbf{Optimization approach}
OS               Dyn. simh. longer CP-SAT 1                9031.40$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 2                9305.60$_{(40\%)}$
                 Dyn. simh. longer CP-SAT 3       \textbf{8981.45}$_{(50\%)}$
                 Dyn. simh. longer CP-SAT 4                9048.15$_{(20\%)}$
PM               Dyn. simh. longer CP-SAT 1                 121.85$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 2                  89.70$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3         \textbf{74.90}$_{(60\%)}$
                 Dyn. simh. longer CP-SAT 4                  82.30$_{(20\%)}$
HFS              Dyn. simh. longer CP-SAT 1        \textbf{141.10}$_{(35\%)}$
                 Dyn. simh. longer CP-SAT 2                 143.55$_{(60\%)}$
                 Dyn. simh. longer CP-SAT 3                 144.50$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 4                 146.15$_{(30\%)}$
JS               Dyn. simh. longer CP-SAT 1      \textbf{36279.45}$_{(30\%)}$
                 Dyn. simh. longer CP-SAT 2               37971.05$_{(20\%)}$
                 Dyn. simh. longer CP-SAT 3               37046.45$_{(40\%)}$
                 Dyn. simh. longer CP-SAT 4               37259.85$_{(10\%)}$
FJS              Dyn. simh. longer CP-SAT 1                8425.70$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 2                8675.05$_{(15\%)}$
                 Dyn. simh. longer CP-SAT 3       \textbf{7779.15}$_{(45\%)}$
                 Dyn. simh. longer CP-SAT 4                8815.45$_{(30\%)}$
Summary results parameter tuning dynamic simheuristic (longer CP-SAT time) for all problems with tardiness objective. Best values marked in \textbf{bold}. If a method is significantly better than others, it is marked with superscript in parentheses: $i$ stands for dynamic simheuristic longer $i$. The percentage in parentheses indicates how often the method was the best across all seeds.
Latex table saved to latex/param_tuning_dyn_simh_long_with_tardiness.tex